# Generated by Django 2.0.2 on 2018-07-17 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import test1.models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
        migrations.AlterField(
            model_name='friend',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='friend',
            name='mail',
            field=models.EmailField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=100, validators=[test1.models.number_only]),
        ),
        migrations.AddField(
            model_name='message',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.Friend'),
        ),
    ]
